### ISSUE TITLE
Java Code for Maximal Square

### ISSUE THREAD

**Issue by navya-Singla-1-3-0-9** [Sagar0-0/DsA#432]
Hey!
I would like to contribute the solution for this problem in Java.
https://leetcode.com/problems/maximal-square/
Please assign this issue to me

**Comment by Sagar0-0** [comment]
Create a PR and tag this issue there.

**Comment by Sagar0-0** [comment]
This repo supports adding code files directly in PRs(after reading Contributing.md). If you were found creating unnecessary Issues/PRs, then this can lead to a permanent ban or disqualification from hacktoberfest.
