### ISSUE TITLE
Java Solution for Three Sum Problem

### ISSUE THREAD

**Issue by codingis4noobs2** [Sagar0-0/DsA#433]
Hey @Sagar0-0  ,
I would like to contribute the solution for this problem in Java.
https://leetcode.com/problems/3sum/
Please assign this issue to me :)

**Comment by Rohans-7** [comment]
I would like to contribute for this problem. Please assign this to me.

**Comment by Sagar0-0** [comment]
Create your PR and tag this issue there.

> Hey @Sagar0-0 , I would like to contribute the solution for this problem in Java. https://leetcode.com/problems/3sum/ Please assign this issue to me :)

**Comment by Sagar0-0** [comment]
This repo supports adding code files directly in PRs(after reading Contributing.md). If you were found creating unnecessary Issues/PRs, then this can lead to a permanent ban or disqualification from hacktoberfest.
