### ISSUE TITLE
Java solution for The Skyline Problem 

### ISSUE THREAD

**Issue by Umang-Bariya** [Sagar0-0/DsA#435]
Hey!
I would like to contribute the solution for this problem in Java.
https://leetcode.com/problems/the-skyline-problem/
Please assign this issue to me.

**Comment by Sagar0-0** [comment]
This repo supports adding code files directly in PRs(after reading Contributing.md). If you were found creating unnecessary Issues/PRs, then this can lead to a permanent ban or disqualification from hacktoberfest.
